<?php
define("_Login","Log in");
define("_Logout","Log out");
define("_StartYourSession","Sign in to start your session");
define("_Email","Email");
define("_Password","Password");
define("_RememberMe","Remember Me");
define("_SignIn","Sign in");
define("_FaceebookSignIn","Sign in using Facebook");
define("_GoogleSignIn","Sign in using Google");
define("_ForgotPassword","I forgot my password");
define("_NewMembership","Register a new membership");
define("_Home","Home");
define("_Welcome","Welcome");
define("_Turk","Turk");
define("_English","English");
define("_Trips","Trips");
define("_New","New");
define("_Profile","Profile");
?>